name: Printful Catalog Split Run (v2, EU-only, adaptive)

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Quelle partie lancer"
        type: choice
        required: true
        default: rest
        options: [rest, core, both]
      page_limit:
        description: "Taille de page API (100–200 recommandé)"
        required: false
        default: "150"
      concurrency:
        description: "Concurrence initiale (variants) – 4..12"
        required: false
        default: "8"
      eu_only:
        description: "Filtrer EU uniquement ?"
        type: choice
        options: ["true", "false"]
        required: false
        default: "true"

env:
  BASE_URL: "https://api.printful.com"

jobs:
  rest:
    name: REST (EU-only) — cats, countries, product mappings, images, availability, prices, sizes
    if: ${{ inputs.part == 'rest' || inputs.part == 'both' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run REST script
        run: node scripts/rest/run_rest.mjs
        env:
          PRINTFUL_TOKEN: ${{ secrets.PRINTFUL_TOKEN }}
          PAGE_LIMIT: ${{ inputs.page_limit }}
          BASE_URL: ${{ env.BASE_URL }}
          CONCURRENCY: ${{ inputs.concurrency }}
          LOG_EVERY: "200"
          EU_ONLY: ${{ inputs.eu_only }}
          EU_COUNTRIES: "AT,BE,BG,HR,CY,CZ,DK,EE,FI,FR,DE,GR,HU,IE,IT,LV,LT,LU,MT,NL,PL,PT,RO,SK,SI,ES,SE,GB,NO,CH,IS,LI"

      - name: Upload CSV artifacts (REST)
        uses: actions/upload-artifact@v4
        with:
          name: csv-rest
          path: data/*.csv
          if-no-files-found: warn

  core:
    name: CORE (EU-only) — products, variants
    if: ${{ inputs.part == 'core' || inputs.part == 'both' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CORE script
        run: node scripts/core/run_core.mjs
        env:
          PRINTFUL_TOKEN: ${{ secrets.PRINTFUL_TOKEN }}
          PAGE_LIMIT: ${{ inputs.page_limit }}
          BASE_URL: ${{ env.BASE_URL }}
          EU_ONLY: ${{ inputs.eu_only }}
          LOG_EVERY: "200"

      - name: Upload CSV artifacts (CORE)
        uses: actions/upload-artifact@v4
        with:
          name: csv-core
          path: |
            data/products.csv
            data/variants.csv
          if-no-files-found: warn
